# Generated by Django 2.2.4 on 2022-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=40)),
                ('email_address', models.EmailField(max_length=70)),
                ('country', models.CharField(max_length=20)),
                ('code', models.IntegerField(max_length=8)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
